---
title: "Chances vs Single Opponent"
geometry: margin=1cm
output: html_document
fontsize: 10pt
---

```{r Setup knitr, include=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, tidy=TRUE, cache=FALSE, OutDec = ",")
```

```{r Load db and RData, include=F}
library( njdanalytics )

nhl_db <- setup_nhl_db()
player_tbl           <- tbl( nhl_db, "player"           ) %>% collect()
team_score           <- tbl( nhl_db, "team_score"       )
stage_game           <- tbl( nhl_db, "stage_game"       )
stage_roster         <- tbl( nhl_db, "stage_roster"     )
stage_playbyplay     <- tbl( nhl_db, "stage_playbyplay" )
game_player          <- tbl( nhl_db, "game_player"      )
team_tbl             <- tbl( nhl_db, "team"             ) %>% collect()

this_season     <- "20152016"
this_session_id <- "2"

# fig directory
fig_dir <- paste0( nhl_dir$shot, "/opponent/fig" )

#########################################################################
# MANUALLY UPDATE
game_suffix <- 79
this_opp_team_short <- "TBL"
#########################################################################

# njd_games has game_number and game_id4 to join different data sources
our_team_short <- "NJD" # might change perspective for games we're not in?
our_games            <- team_score %>% 
                          filter( season==this_season, session_id==this_session_id, team_short==our_team_short) %>%
                          collect() %>% arrange( game_date )
our_games            <- add_team_score_label( our_games, our_team=our_team_short ) %>%
                          select( game_date, game_number, season, session_id, game_id4, ha, opp_team_short, game_label )
our_game_id4s        <- our_games$game_id4

# njd_games, shots_tbl, player_chances_df, njd_players_by_game, pair_chances_df
load( file=paste0( nhl_dir$shot, "/njd_through_", game_suffix, ".RData" ))
```


```{r opp data}
opp_team_short_lower <- this_opp_team_short %>% str_to_lower()
vs_opp_games         <- our_games %>% filter( opp_team_short==this_opp_team_short )
our_team_common      <- team_tbl %>% filter( name_short==our_team_short      ) %>% select( name_common ) %>% unlist( use.names = F )
opp_team_common      <- team_tbl %>% filter( name_short==this_opp_team_short ) %>% select( name_common ) %>% unlist( use.names = F )

vs_opp_games

######################### FILTER GAMES
vs_opp_games %<>% slice(-1)


# drop any games as needed
# vs_opp_games        <- vs_opp_games %>% slice(-1)
vs_opp_game_id4s    <- c( "0", vs_opp_games$game_id4 )  # dummy game to make the %in% filter possible

# Note: game_h2h is symmetric: (player_A, Player_B) and (player_B, player_A) are both in table
toi_h2h_ev_gm       <- tbl( nhl_db, "game_h2h" ) %>% filter( season==this_season, game_id4 %in% vs_opp_game_id4s,
                                                     filter_score_diff=="all", filter_strength=="ev5on5" ) %>% collect()
vs_opp_rosters      <- stage_roster %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% vs_opp_game_id4s ) %>% collect()
vs_opp_pbp          <- stage_playbyplay %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% vs_opp_game_id4s ) %>% collect()
vs_opp_stage_game   <- stage_game %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% vs_opp_game_id4s ) %>% collect()

vs_opp_pair_chances <- pair_chances_df %>% filter( game_id4 %in% vs_opp_game_id4s ) %>% select( -starts_with( "ha_number" ))
sc_h2h_ev_gm       <- vs_opp_pair_chances %>% filter( strength=="ev5on5" )

player_chances_vs_opp <- player_chances_df %>% filter( season==this_season, game_id4 %in% vs_opp_game_id4s )
sc_by_game_green_ev <- player_chances_vs_opp %>% filter( strength=="ev5on5", metric=="green", last_name=="NJD" )

sc_by_game_green_ev <- sc_by_game_green_ev %>% left_join( vs_opp_games, by = c( "season", "session_id", "game_id4", "game_number" ) )

sc_by_game_green_ev
```

```{r EV PP TOI}
njd_game_player      <- game_player %>% 
                          filter( season==this_season, session_id==this_session_id, team_short==our_team_short, game_id4 %in% vs_opp_game_id4s,
                                  nhl_id==1,
                                  filter_period=="all", filter_score_diff=="all", 
                                  filter_strength %in% c( "ev5on5", "sh", "pp", "own_en", "comp_en" ) ) %>% collect()

njd_stage_game      <- stage_game %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% vs_opp_game_id4s ) %>% collect()

njd_toi <- njd_game_player %>% select( game_date, filter_strength, toi )

```

```{r}

pp_results_list <- vector("list", nrow(vs_opp_games))
for( i in 1:nrow(vs_opp_games) ) {
  pp_results_list[[i]] <- get_pp_results( this_season, this_session_id, vs_opp_games$game_id4[i], team_tbl )  
}

pp_results <- do.call( "rbind", pp_results_list )
pp_results <- pp_results %>% left_join( vs_opp_games, by=c( "season", "session_id", "game_id4" ) )

pp_results

# summary by team
pp_results %>% group_by( team_short ) %>% summarize( goals=sum(goals), ppo=sum(ppo), time=sum(time) )
```


```{r augment data}
# 1. add faceoff count, is_center, num_last_name.  
# 2. Sort rosters of teams, ORDERED F/D/G, with F in groups of 4 lines (C first), D in 3 pairings (L then R shot).
# Highest TOI/gm C is first of F, highest TOI/gm D is first pairing.
# Excess F and D are appended on to F and D groups respectively.

if( nrow(vs_opp_games) == 1 ) {
  num_centers <- 4
} else {
  num_centers <- 5
}

## CAR and NJD have 4 C
# but, need to figure out a better way to do this
num_centers <- 4
#################################

vs_opp_rosters_C      <- augment_rosters_C( vs_opp_rosters, vs_opp_pbp, player_tbl, center_fo_cutoff = num_centers  )
```

```{r opp data fidgeting}

# # override C
# vs_opp_rosters_C$is_center[ vs_opp_rosters_C$team_short=="CAR"] <- FALSE
# # manullay add C of my choosing
# vs_opp_rosters_C$is_center[ vs_opp_rosters_C$num_last_name=="11 STAAL"     ] <- TRUE
# vs_opp_rosters_C$is_center[ vs_opp_rosters_C$num_last_name=="49 RASK"      ] <- TRUE
# vs_opp_rosters_C$is_center[ vs_opp_rosters_C$num_last_name=="18 MCCLEMENT" ] <- TRUE
# vs_opp_rosters_C$is_center[ vs_opp_rosters_C$num_last_name=="20 NASH"      ] <- TRUE

vs_opp_rosters_group  <- group_multigame_rosters_by_lines( vs_opp_rosters_C, toi_h2h_ev_gm )
```

```{r aggregate data}
# Aggregate by pairs (p1, p2) across games
toi_h2h_ev <- aggregate_toi_h2h( toi_h2h_ev_gm, vs_opp_rosters_group )
sc_h2h_ev  <- aggregate_sc_h2h(   sc_h2h_ev_gm, vs_opp_rosters_group )

sc_h2h_green <- sc_h2h_ev %>% filter( metric=="green" )
sc_h2h_blue  <- sc_h2h_ev %>% filter( metric=="blue"  )

h2h_ev <- toi_h2h_ev %>% left_join( sc_h2h_green %>% select( nhl_id_1, nhl_id_2, green_f=scf, green_a=sca, green_net=sc_net ),
                                 by=c( "nhl_id_1", "nhl_id_2" ) ) %>% 
                         left_join( sc_h2h_blue  %>% select( nhl_id_1, nhl_id_2, blue_f=scf,  blue_a=sca,  blue_net=sc_net ),
                                 by=c( "nhl_id_1", "nhl_id_2" ) )

h2h_ev <- h2h_ev %>% mutate(
                        green_f_60   = round( green_f   / toi * 60, 3 ),
                        green_a_60   = round( green_a   / toi * 60, 3 ),
                        green_net_60 = round( green_net / toi * 60, 3 ),
                        blue_f_60    = round( blue_f    / toi * 60, 3 ),
                        blue_a_60    = round( blue_a    / toi * 60, 3 ),
                        blue_net_60  = round( blue_net  / toi * 60, 3 )
          )
h2h_ev[ is.na(h2h_ev) ] <- 0

```


```{r line adjustments}

row_num_last_names <- vs_opp_rosters_group %>% filter( team_short==our_team_short,      position_fd != "G" ) %>% 
                                            select( num_last_name ) %>% unlist(use.names = F)
col_num_last_names <- vs_opp_rosters_group %>% filter( team_short==this_opp_team_short, position_fd != "G" ) %>% 
                                            select( num_last_name ) %>% unlist(use.names = F)

# custom_opp_1st_line <- c( "92 KUZNETSOV", "8 OVECHKIN", "14 WILLIAMS" )
# opp_num_last_names  <- c( custom_opp_1st_line, col_num_last_names[!col_num_last_names %in% custom_opp_1st_line])
# col_num_last_names  <- opp_num_last_names

```


```{r data C only}
h2h_ev_C  <- h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==this_opp_team_short,
                          is_center_1, is_center_2)
us_ev_C   <- h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==our_team_short,
                          is_center_1, is_center_2)
them_ev_C <- h2h_ev %>% filter( team_short_1==this_opp_team_short, team_short_2==this_opp_team_short,
                          is_center_1, is_center_2)

row_num_last_names_C <- vs_opp_rosters_group %>% filter( team_short==our_team_short, is_center ) %>% 
                                            select( num_last_name ) %>% unlist(use.names = F)
col_num_last_names_C <- vs_opp_rosters_group %>% filter( team_short==this_opp_team_short, is_center ) %>% 
                                            select( num_last_name ) %>% unlist(use.names = F)

# col_num_last_names_C <- opp_num_last_names[ opp_num_last_names %in% col_num_last_names_C ]
```

```{r data our D their F}
our_D_their_F <- h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==this_opp_team_short,
                                    position_fd_1=="D", position_fd_2=="F" )

row_num_last_names_D <- vs_opp_rosters_group %>% filter( team_short==our_team_short, position_fd=="D" ) %>% 
                                            select( num_last_name ) %>% unlist(use.names = F)
col_num_last_names_F <- vs_opp_rosters_group %>% filter( team_short==this_opp_team_short,  position_fd=="F" ) %>% 
                                            select( num_last_name ) %>% unlist(use.names = F)

# custom order
# col_num_last_names_F <- opp_num_last_names[ opp_num_last_names %in% col_num_last_names_F ]

this_row_num_D <- length( row_num_last_names_D )
this_row_num_F <- length( row_num_last_names ) - this_row_num_D
this_col_num_F <- length( col_num_last_names_F )
this_col_num_D <- length( col_num_last_names ) - this_col_num_F
this_row_num_D_pairs <- this_row_num_D %/% 2
this_col_num_D_pairs <- this_col_num_D %/% 2
this_row_num_F_lines <- this_row_num_F %/% 3
this_col_num_F_lines <- this_col_num_F %/% 3

# override
this_row_num_F_lines <- 4
this_col_num_F_lines <- 4
this_row_num_D_pairs <- 3
this_col_num_D_pairs <- 3
```

```{r data our F their F}
our_F_their_F <- h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==this_opp_team_short,
                                    position_fd_1=="F", position_fd_2=="F" )

our_C_their_F <- h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==this_opp_team_short,
                                    is_center_1, position_fd_1=="F", position_fd_2=="F" )

row_num_last_names_F <- vs_opp_rosters_group %>% filter( team_short==our_team_short, position_fd=="F" ) %>% 
                                            select( num_last_name ) %>% unlist(use.names = F)
```

```{r data our D only}
our_D <-  h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==our_team_short,
                                    position_fd_1=="D", position_fd_2=="D" )

our_F <-  h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==our_team_short,
                                    position_fd_1=="F", position_fd_2=="F" )

their_F <-  h2h_ev %>% filter( team_short_1==this_opp_team_short, team_short_2==this_opp_team_short,
                                    position_fd_1=="F", position_fd_2=="F" )
```


```{r chart all players}

gtitle <- paste0( "EV5on5 TOI" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_TOI.png" )
create_heatmap_from_h2h( h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==this_opp_team_short ),
                          value_type="toi", 
                          row_num_last_names, col_num_last_names,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=this_col_num_D_pairs,
                          row_num_D=this_row_num_D, col_num_D=this_col_num_D,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 Green Chance Differential" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_green.png" )
create_heatmap_from_h2h( h2h_ev %>% filter( team_short_1==our_team_short, team_short_2==this_opp_team_short ),
                          value_type="green_net", 
                          row_num_last_names, col_num_last_names,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=this_col_num_D_pairs,
                          row_num_D=this_row_num_D, col_num_D=this_col_num_D,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname )
```


```{r chart our D only}
# NJD ONLY
gtitle <- paste0( "EV5on5 TOI Devils D Pairings" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_D_TOI.png" )
create_heatmap_from_h2h( our_D, value_type="toi", row_num_last_names_D, row_num_last_names_D,
                          row_num_F_lines=0, col_num_F_lines=0,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=this_row_num_D_pairs,
                          row_num_D=this_row_num_D, col_num_D=this_row_num_D,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 Green Chances Devils D Pairings" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_D_green.png" )
create_heatmap_from_h2h( our_D, value_type="green_net", row_num_last_names_D, row_num_last_names_D,
                          row_num_F_lines=0, col_num_F_lines=0,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=this_row_num_D_pairs,
                          row_num_D=this_row_num_D, col_num_D=this_row_num_D,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 Blue Chances Devils D Pairings" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_D_blue.png" )
create_heatmap_from_h2h( our_D, value_type="blue_net", row_num_last_names_D, row_num_last_names_D,
                          row_num_F_lines=0, col_num_F_lines=0,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=this_row_num_D_pairs,
                          row_num_D=this_row_num_D, col_num_D=this_row_num_D,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )
```


```{r chart our F only}
# NJD ONLY
gtitle <- paste0( "EV5on5 TOI ", our_team_common, " Forwards" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_F_TOI.png" )
create_heatmap_from_h2h( our_F, value_type="toi", row_num_last_names_F, row_num_last_names_F,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_row_num_F_lines,
                          row_num_D_pairs=0, col_num_D_pairs=0,
                          row_num_D=0, col_num_D=0,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 Green chances ", our_team_common, " Forwards" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_F_green.png" )
create_heatmap_from_h2h( our_F, value_type="green_net", row_num_last_names_F, row_num_last_names_F,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_row_num_F_lines,
                          row_num_D_pairs=0, col_num_D_pairs=0,
                          row_num_D=0, col_num_D=0,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 Blue chances ", our_team_common, " Forwards" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_F_blue.png" )
create_heatmap_from_h2h( our_F, value_type="blue_net", row_num_last_names_F, row_num_last_names_F,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_row_num_F_lines,
                          row_num_D_pairs=0, col_num_D_pairs=0,
                          row_num_D=0, col_num_D=0,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )
```

```{r chart their F only}
# NJD ONLY
gtitle <- paste0( "EV5on5 TOI ", opp_team_common, " Forwards" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_their_F_TOI.png" )
create_heatmap_from_h2h( their_F, value_type="toi", col_num_last_names_F, col_num_last_names_F,
                          row_num_F_lines=this_col_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0, col_num_D_pairs=0,
                          row_num_D=0, col_num_D=0,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 Green chances ", opp_team_common, " Forwards" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_their_F_green.png" )
create_heatmap_from_h2h( their_F, value_type="green_net", col_num_last_names_F, col_num_last_names_F,
                          row_num_F_lines=this_col_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0, col_num_D_pairs=0,
                          row_num_D=0, col_num_D=0,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 Blue chances ", opp_team_common, " Forwards" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_their_F_blue.png" )
create_heatmap_from_h2h( their_F, value_type="blue_net", col_num_last_names_F, col_num_last_names_F,
                          row_num_F_lines=this_col_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0, col_num_D_pairs=0,
                          row_num_D=0, col_num_D=0,
                          row_axis_title = "", col_axis_title = "", chart_title = gtitle,
                          chart_filename=fname )
```

```{r chart our D their F}

gtitle <- paste0( "EV5on5 H2H TOI" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_D_vs_F_TOI.png" )

create_heatmap_from_h2h( our_D_their_F, value_type="toi", row_num_last_names_D, col_num_last_names_F,
                          row_num_F_lines=0, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=0,
                          row_num_D=this_row_num_D, col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname, width_to_height_ratio = 2 )

gtitle <- paste0( "EV5on5 H2H Green Chances" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_D_vs_F_green.png" )

create_heatmap_from_h2h( our_D_their_F, value_type="green_net", row_num_last_names_D, col_num_last_names_F,
                          row_num_F_lines=0, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=0,
                          row_num_D=this_row_num_D, col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname, width_to_height_ratio = 2 )

gtitle <- paste0( "EV5on5 H2H Blue Chances" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_D_vs_F_blue.png" )

create_heatmap_from_h2h( our_D_their_F, value_type="blue_net", row_num_last_names_D, col_num_last_names_F,
                          row_num_F_lines=0, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=this_row_num_D_pairs, col_num_D_pairs=0,
                          row_num_D=this_row_num_D, col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname, width_to_height_ratio = 2 )
```

```{r h2h our F their F}
gtitle <- paste0( "EV5on5 H2H TOI" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_F_TOI.png" )

create_heatmap_from_h2h( our_F_their_F, value_type="toi", row_num_last_names_F, col_num_last_names_F,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0,                    col_num_D_pairs=0,
                          row_num_D=0,                          col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 H2H Green Chances" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_F_green.png" )

create_heatmap_from_h2h( our_F_their_F, value_type="green_net", row_num_last_names_F, col_num_last_names_F,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0,                    col_num_D_pairs=0,
                          row_num_D=0,                          col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname )

gtitle <- paste0( "EV5on5 H2H Blue Chances" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_F_blue.png" )

create_heatmap_from_h2h( our_F_their_F, value_type="blue_net", row_num_last_names_F, col_num_last_names_F,
                          row_num_F_lines=this_row_num_F_lines, col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0,                    col_num_D_pairs=0,
                          row_num_D=0,                          col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname )

```

```{r h2h our C their F}
gtitle <- paste0( "EV5on5 H2H TOI" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_C_vs_F_TOI.png" )
create_heatmap_from_h2h( our_C_their_F, value_type="toi", row_num_last_names_C, col_num_last_names_F,
                          row_num_F_lines=0,                    col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0,                    col_num_D_pairs=0,
                          row_num_D=0,                          col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname, width_to_height_ratio = 2 )

gtitle <- paste0( "EV5on5 H2H Green Chances" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_C_vs_F_green.png" )
create_heatmap_from_h2h( our_C_their_F, value_type="green_net", row_num_last_names_C, col_num_last_names_F,
                          row_num_F_lines=0,                    col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0,                    col_num_D_pairs=0,
                          row_num_D=0,                          col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname, width_to_height_ratio = 2 )

gtitle <- paste0( "EV5on5 H2H Blue Chances" )
fname <-  paste0( fig_dir, "/njd-", opp_team_short_lower, "_our_C_vs_F_blue.png" )
create_heatmap_from_h2h( our_C_their_F, value_type="blue_net", row_num_last_names_C, col_num_last_names_F,
                          row_num_F_lines=0,                    col_num_F_lines=this_col_num_F_lines,
                          row_num_D_pairs=0,                    col_num_D_pairs=0,
                          row_num_D=0,                          col_num_D=0,
                          row_axis_title = our_team_common, col_axis_title = opp_team_common, chart_title = gtitle,
                          chart_filename=fname, width_to_height_ratio = 2 )

```


```{r write chances to table}
player_chances_vs_opp_ev  <- player_chances_vs_opp %>% filter( strength=="ev5on5" )
player_chances_vs_opp_all <- player_chances_vs_opp %>% filter( strength=="all" )
player_chances_vs_opp_pp  <- player_chances_vs_opp %>% filter( strength=="pp" )

player_stats <- player_chances_vs_opp_all %>% filter( metric=="fenwick" ) %>%  group_by( team_short, nhl_id, last_name ) %>% summarize(
  gm = n(),
  toi_total=sum(toi) %>% round(2),
  toi_gm = (toi_total/gm) %>% round(1)
) %>% left_join( player_tbl %>% select( nhl_id, position_fd, number ), by="nhl_id" ) %>%
  ungroup() %>% arrange( team_short, position_fd, desc(toi_gm) )

### EV
player_fenwick_ev <- player_chances_vs_opp_ev %>% filter( metric=="fenwick" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  toi_total_ev=sum(toi) %>% round(3),
  toi_gm_ev=(toi_total_ev/n() ) %>% round(1),
  ff=sum(scf), fa=sum(sca), f_net=sum(sc_net),
  ff_i_ev=sum(scf_i),
  ff_i_60_ev = (ff_i_ev/toi_total_ev*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total_ev )

player_green_ev <- player_chances_vs_opp_ev %>% filter( metric=="green" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  green_f=sum(scf), green_a=sum(sca), green_net=sum(sc_net),
  toi_total_ev=sum(toi) %>% round(2),
  green_i_ev=sum(scf_i),
  green_i_60_ev = (green_i_ev/toi_total_ev*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total_ev )

player_blue_ev <- player_chances_vs_opp_ev %>% filter( metric=="blue" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  blue_f=sum(scf), blue_a=sum(sca), blue_net=sum(sc_net),
  toi_total_ev=sum(toi) %>% round(2),
  blue_i_ev=sum(scf_i),
  blue_i_60_ev = (blue_i_ev/toi_total_ev*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total_ev )

player_greenblue_ev <- player_chances_vs_opp_ev %>% filter( metric=="greenblue" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  greenblue_f=sum(scf), greenblue_a=sum(sca), greenblue_net=sum(sc_net),
  toi_total_ev=sum(toi) %>% round(2),
  greenblue_i_ev=sum(scf_i),
  greenblue_i_60_ev = (greenblue_i_ev/toi_total_ev*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total_ev )

#### ALL
corsi_all <- player_chances_vs_opp_all %>% filter( metric=="corsi" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  toi_total=sum(toi) %>% round(2),
  toi_gm=toi_total/n(),
  cf=sum(scf), ca=sum(sca), c_net=sum(sc_net),
  cf_i=sum(scf_i),
  cf_i_60 = (cf_i/toi_total*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total )

player_fenwick_all <- player_chances_vs_opp_all %>% filter( metric=="fenwick" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  toi_total=sum(toi) %>% round(2),
  toi_gm=toi_total/n(),
  ff=sum(scf), fa=sum(sca), f_net=sum(sc_net),
  ff_i=sum(scf_i),
  ff_i_60 = (ff_i/toi_total*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total )

player_green_pp <- player_chances_vs_opp_pp %>% filter( metric=="green" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  green_f_pp=sum(scf), green_a_pp=sum(sca), green_net_pp=sum(sc_net),
  toi_total=sum(toi) %>% round(2),
  toi_gm_pp = toi_total/n(),
  green_i_pp=sum(scf_i),
  green_i_60 = (green_i_pp/toi_total*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total )

player_blue_pp <- player_chances_vs_opp_pp %>% filter( metric=="blue" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  blue_f_pp=sum(scf), blue_a_pp=sum(sca), blue_net_pp=sum(sc_net),
  toi_total=sum(toi) %>% round(2),
  blue_i_pp=sum(scf_i),
  blue_i_60 = (blue_i_pp/toi_total*60) %>% round(1)
) %>% ungroup() %>% select(-toi_total )

player_green_all <- player_chances_vs_opp_all %>% filter( metric=="green" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  green_i_all=sum(scf_i)
) %>% ungroup()

player_blue_all <- player_chances_vs_opp_all %>% filter( metric=="blue" ) %>%  group_by( nhl_id, last_name ) %>% summarize(
  blue_i_all=sum(scf_i)
) %>% ungroup()

player_stats_retval <- player_stats %>%
  left_join( player_fenwick_ev, by=c("nhl_id", "last_name") ) %>%
  left_join( player_green_ev, by=c("nhl_id", "last_name") ) %>%
  left_join( player_blue_ev, by=c("nhl_id", "last_name") )  %>%
  left_join( player_greenblue_ev, by=c("nhl_id", "last_name") ) %>%
  left_join( corsi_all %>% select( nhl_id, cf_i ), by=c("nhl_id" ) ) %>%
  left_join( player_green_pp %>% select( nhl_id, green_i_pp ), by=c("nhl_id" ) ) %>%
  left_join( player_blue_pp %>% select( nhl_id, blue_i_pp ), by=c("nhl_id" ) ) %>%
  left_join( player_green_all %>% select( nhl_id, green_i_all ), by=c("nhl_id" ) ) %>%
  left_join( player_blue_all %>% select( nhl_id, blue_i_all ), by=c("nhl_id" ) )

player_stats_retval[ is.na(player_stats_retval) ] <- 0

# player_stats <- player_stats %>% mutate(
#   green_i_other = green_i - green_i_ev,
#   blue_i_other  = blue_i - blue_i_ev
# )

# SORT PLAYERS IF ONLY ONE GAME

player_stats_retval <- player_stats_retval %>% left_join( vs_opp_rosters_group %>% select( nhl_id, rank), by="nhl_id" ) %>%
  arrange( rank )

# player_stats_brief <- player_stats_retval %>% select( team_short, last_name, number, position_fd,
#   gm, toi_gm, toi_gm_ev,
#   green_net, blue_net, greenblue_net,
#   green_i_ev, green_i_pp, blue_i_ev, blue_i_pp, cf_i )
#
# brief_col_names <- c( "Team", "Player", "Number", "Pos", "Games", "TOI/Gm", "TOI/Gm EV", "Green Net", "Blue Net", "Green or Blue Net",
#   "Green i EV", "Green i PP",
#   "Blue i EV", "Blue i PP",
#   "Shot Attempts Individual" )

player_stats_brief <- player_stats_retval %>% select( team_short, last_name, number, position_fd,
  gm, toi_gm, toi_gm_ev,
  green_net, blue_net, greenblue_net,
  green_i_all, blue_i_all, cf_i )

brief_col_names <- c( "Team", "Player", "Number", "Pos", "Games", "TOI/Gm", "TOI/Gm EV", "Green Net", "Blue Net", "Green or Blue Net",
  "Green i",
  "Blue i",
  "Shot Attempts Individual" )

player_stats_brief <- player_stats_brief %>% filter( position_fd != "G" )
names(player_stats_brief) <- brief_col_names

# write_csv( player_stats_brief, path=paste0(nhl_dir$shot, "/opponent/NJD_through_gm50.csv") )

stats_filename <- paste0(nhl_dir$shot, "/opponent/", this_opp_team_short, ".csv")
message( "Write stats to ", stats_filename )
write_csv( player_stats_brief, path= stats_filename )

```
```{r chances summary}
player_chances_vs_opp_ev %>% filter( metric=="green", last_name=="NJD" )
player_chances_vs_opp_ev %>% filter( metric=="blue", last_name=="NJD" )

player_chances_vs_opp_all %>% filter( metric=="green", last_name=="NJD" )
player_chances_vs_opp_all %>% filter( metric=="blue", last_name=="NJD" )

player_chances_vs_opp_ev  <- player_chances_vs_opp %>% filter( strength=="ev5on5" )
player_chances_vs_opp_all <- player_chances_vs_opp %>% filter( strength=="all" )
player_chances_vs_opp_pp  <- player_chances_vs_opp %>% filter( strength=="pp" )

sc_green_summary_ev <- player_chances_vs_opp_ev %>% filter( metric=="green", last_name=="NJD" ) %>% summarize( scf=sum(scf), sca=sum(sca), sc_net=sum(sc_net), cf=sum(cf), ca=sum(ca), c_net=sum(c_net), ff=sum(ff), fa=sum(fa), f_net=sum(f_net) )
sc_blue_summary_ev  <- player_chances_vs_opp_ev %>% filter( metric=="blue", last_name=="NJD" ) %>% summarize( scf=sum(scf), sca=sum(sca), sc_net=sum(sc_net), cf=sum(cf), ca=sum(ca), c_net=sum(c_net), ff=sum(ff), fa=sum(fa), f_net=sum(f_net) )

sc_green_summary_all <- player_chances_vs_opp_all %>% filter( metric=="green", last_name=="NJD" ) %>% summarize( scf=sum(scf), sca=sum(sca), sc_net=sum(sc_net), cf=sum(cf), ca=sum(ca), c_net=sum(c_net), ff=sum(ff), fa=sum(fa), f_net=sum(f_net) )
sc_blue_summary_all <- player_chances_vs_opp_all %>% filter( metric=="blue", last_name=="NJD" ) %>% summarize( scf=sum(scf), sca=sum(sca), sc_net=sum(sc_net), cf=sum(cf), ca=sum(ca), c_net=sum(c_net), ff=sum(ff), fa=sum(fa), f_net=sum(f_net) )


sc_green_summary_ev
sc_blue_summary_ev

sc_green_summary_all - sc_green_summary_ev
sc_blue_summary_all - sc_blue_summary_ev



# player_chances_vs_opp_ev %>% filter( metric=="green", last_name %in% c( "KUZNETSOV", "OVECHKIN", "WILLIAMS") )
# player_chances_vs_opp_ev %>% filter( metric=="green", last_name %in% c( "BACKSTROM", "OSHIE", "BURAKOVSKY") )
# 
# player_chances_vs_opp_ev %>% filter( metric=="green", last_name %in% c( "HENRIQUE", "ZAJAC") )
# player_chances_vs_opp_ev %>% filter( metric=="green", last_name %in% c( "GREENE") )

```
