---
  title: "NHL Official Shot Tallies"
geometry: margin=1cm
output: html_document
fontsize: 10pt
---

  ```{r Setup knitr, include=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, tidy=TRUE, cache=TRUE, OutDec = ",")
```

```{r Load db and RData, include=F}
library( njdanalytics )

nhl_db <- setup_nhl_db()
team_score           <- tbl( nhl_db, "team_score"       )
stage_pbp            <- tbl( nhl_db, "stage_playbyplay" )
game_player          <- tbl( nhl_db, "game_player"      )
team_tbl             <- tbl( nhl_db, "team"             ) %>% collect()

this_season     <- "20152016"
this_session_id <- "2"

# fig directory
fig_dir <- paste0( nhl_dir$base, "/packages/njdanalytics/sandbox/fig/njd2016/f_lines" )

#################################``########################################
# MANUALLY UPDATE
game_suffix <- 82

#########################################################################

# njd_games has game_number and game_id4 to join different data sources
our_team_short  <- "NJD" # might change perspective for games we're not in?
our_team_common <- team_tbl %>% filter( name_short==our_team_short ) %>% select( name_common ) %>% unlist( use.names = F )
our_games       <- team_score %>%
                        filter( season==this_season, session_id==this_session_id, team_short==our_team_short) %>%
                        collect() %>% arrange( game_date )
our_games            <- add_team_score_label( our_games, our_team=our_team_short ) %>%
                          select( game_date, game_number, season, session_id, game_id4, ha, opp_team_short, game_label )
our_game_id4s        <- our_games$game_id4

# njd_games, shots_tbl, player_chances_df, njd_players_by_game, pair_chances_df
load( file=paste0( nhl_dir$shot, "/njd_through_", game_suffix, ".RData" ))
```


```{r analysis parameters}
this_season     <- "20152016"
this_session_id <- "2"
```

```{r NHL official shots}
our_gp <- game_player %>%
  filter( season==this_season, session_id==this_session_id, game_id4 %in% our_game_id4s,
          filter_period=="all", filter_score_diff=="all", nhl_id==1, filter_strength %in% c( "ev5on5", "all" ) ) %>% collect()

our_pbp <- stage_pbp %>%
              filter( season==this_season, session_id==this_session_id, game_id4 %in% our_game_id4s ) %>% collect()
```

```{r NJD video based shots}
njd_team_shots <- njd_players_by_game %>% filter( last_name=="NJD", 
                                          metric %in% c( "corsi", "fenwick"), strength %in% c( "ev5on5", "all")) %>% 
                    select( -ha_number, -scf_i, -nhl_id, -last_name, -toi, -position_fd, -number, -team_short ) %>% as_data_frame()

njd_team_shots <- njd_team_shots %>% mutate(
    c_total = cf+ca,
    cf_pct  = round( cf/c_total*100, 1 ),
    f_total = ff+fa,
    ff_pct  = round( ff/f_total*100, 1 ),
    c_diff  = sc_total - c_total,
    cf_pct_diff = scf_pct -cf_pct,
    c_diff_pct = round( c_diff/sc_total*100, 1 )
)

p.shots <- ggplot( njd_team_shots %>% filter(strength=="all", metric=="corsi"), aes(x=game_number, y=c_diff))
p.shots + geom_bar( stat="identity" )

```

```{r bad games}
# 4, 57, 81, 73, 77, 82
#   game_number   season session_id game_id4    ha opp_team_short                  game_label
#         <int>    <chr>      <chr>    <chr> <chr>          <chr>                      <fctr>
# 1           4 20152016          2     0058     H            SJS G4 OTL\n10/16 SJS\n2-1 (SO)
# 2          57 20152016          2     0836     H            LAK       G57 W\n02/14 LAK\n0-1
# 3          81 20152016          2     1203     H            TBL       G81 L\n04/07 TBL\n4-2
# 4          73 20152016          2     1079     H            CBJ       G73 W\n03/20 CBJ\n1-2
# 5          77 20152016          2     1140     H            BOS       G77 W\n03/29 BOS\n1-2
# 6          82 20152016          2     1222     H            TOR       G82 W\n04/09 TOR\n1-5



shots_57 <- our_pbp %>% filter( game_id4=="0836", event_type %in% c( "GOAL", "SHOT", "MISS", "BLOCK" ) )

shots_all_df %>% filter( game_id4=="0836" ) 

# EV5on5
njd_team_shots %>% filter( game_id4=="0836", strength=="ev5on5", metric=="corsi") %>% glimpse


this_period <- 3
shots_57 %>% filter( period==this_period) %>% group_by( event_team, event_type ) %>% summarise( count=n() )



shots_all_df %>% filter( game_id4=="0836", period==this_period ) %>% group_by( event_team, shot ) %>% 
    summarise( count=n() )

shots_all_df %>% filter( game_id4=="0836", period==this_period )
```


```{r season diff}
njd_team_shots %>% filter( strength=="ev5on5", metric=="corsi") %>% summarise(
  scf=sum(scf),
  sca=sum(sca),
  sc_total=sum(sc_total),
  scf_pct=round( scf/sc_total*100, 1),
  cf=sum(cf),
  ca=sum(ca),
  c_total=cf + ca,
  cf_pct=round( cf/c_total*100, 1)
)

```













