---
title: "NJD Chances by Line"
geometry: margin=1cm
output: html_document
fontsize: 10pt
---

```{r Setup knitr, include=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, tidy=TRUE, cache=TRUE, OutDec = ",")
```

```{r Load db and RData, include=F}
library( njdanalytics )

nhl_db <- setup_nhl_db()
player_tbl           <- tbl( nhl_db, "player"           ) %>% collect()
team_score           <- tbl( nhl_db, "team_score"       )
stage_game           <- tbl( nhl_db, "stage_game"       )
stage_roster         <- tbl( nhl_db, "stage_roster"     )
stage_playbyplay     <- tbl( nhl_db, "stage_playbyplay" )
stage_shift_interval <- tbl( nhl_db, "stage_shift_interval" )
game_player          <- tbl( nhl_db, "game_player"      )
team_tbl             <- tbl( nhl_db, "team"             ) %>% collect()

this_season     <- "20152016"
this_session_id <- "2"

# fig directory
fig_dir <- paste0( nhl_dir$base, "/packages/njdanalytics/sandbox/fig/njd2016/f_lines" )

#################################``########################################
# MANUALLY UPDATE
game_suffix <- 82

#########################################################################

# njd_games has game_number and game_id4 to join different data sources
our_team_short  <- "NJD" # might change perspective for games we're not in?
our_team_common <- team_tbl %>% filter( name_short==our_team_short ) %>% select( name_common ) %>% unlist( use.names = F )
our_games       <- team_score %>% 
                          filter( season==this_season, session_id==this_session_id, team_short==our_team_short) %>%
                          collect() %>% arrange( game_date )
our_games            <- add_team_score_label( our_games, our_team=our_team_short ) %>%
                          select( game_date, game_number, season, session_id, game_id4, ha, opp_team_short, game_label )
our_game_id4s        <- our_games$game_id4

# njd_games, shots_tbl, player_chances_df, njd_players_by_game, pair_chances_df
load( file=paste0( nhl_dir$shot, "/njd_through_", game_suffix, ".RData" ))
```


```{r analysis parameters}
this_season     <- "20152016"
this_session_id <- "2"
```

```{r db tables}
rosters      <- stage_roster %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% our_game_id4s ) %>% collect()
pbp          <- stage_playbyplay %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% our_game_id4s ) %>% collect()
stage_game   <- stage_game %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% our_game_id4s ) %>% collect()
stage_roster <- stage_roster %>% 
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% our_game_id4s ) %>% 
                          collect() %>% mutate(
                            position_fd = ifelse( position=="G", "G", ifelse( position=="D", "D", "F") )
                          )

# 21.9k rows in our shift interval
stage_shift_interval <- stage_shift_interval %>%
                          filter( season==this_season, session_id==this_session_id, game_id4 %in% our_game_id4s ) %>% collect()
```

```{r shift interval nest}
# Get HA perspective joined
shift_interval_spread <- stage_shift_interval %>% 
    left_join( our_games %>% select( season, game_id4, our_ha=ha ), by=c( "season", "game_id4" ) ) %>% 
    mutate(
      ev5on5    = ifelse( num_skaters_h==5 & num_goalies_h==1 & num_skaters_a==5 & num_goalies_a==1, TRUE, FALSE ),
      our_num_players   = ifelse( our_ha=="H", num_players_h, num_players_a ),
      their_num_players = ifelse( our_ha=="H", num_players_a, num_players_h ),
      our_num_skaters   = ifelse( our_ha=="H", num_skaters_h, num_skaters_a ),
      our_num_goalies   = ifelse( our_ha=="H", num_goalies_h, num_goalies_a ),
      their_num_skaters = ifelse( our_ha=="H", num_skaters_a, num_skaters_h ),
      their_num_goalies = ifelse( our_ha=="H", num_goalies_a, num_goalies_h ),
      strength          = ifelse( our_num_players > their_num_players, "pp", 
                           ifelse( our_num_players < their_num_players, "sh", "ev" ) ),
      skater_count = paste0( our_num_skaters, "on", their_num_skaters ),
      skater_count = ifelse( !our_num_goalies, paste0( skater_count, "_our_en"),
                        ifelse( !their_num_goalies, paste0( skater_count, "_their_en"), skater_count ) )
    )

# CHECK
shift_interval_spread %>% group_by( #our_num_skaters, their_num_skaters, our_num_goalies, their_num_goalies, 
                                  strength, skater_count ) %>% summarise( toi=sum(duration) ) %>% ungroup() %>% 
                          arrange( desc(toi)) %>% as.data.frame()

# Gather away_p1_id - home_p6_id columns and convert to rows.
# Each unique time interval with then have multiple rows, one for each on ice player.
shift_interval_gather <- shift_interval_spread %>% gather( player_label, player_id, away_p1_id:home_p6_id ) %>% 
                          filter( !is.na(player_id) ) %>% 
                          left_join(
                            player_tbl %>% select( nhl_id, last_name, position_fd ), by=c( "player_id"="nhl_id" )
                          ) %>% mutate(
                            player_ha = ifelse( grepl( "home", player_label ), "H", "A" )
                          )

# Drop extra columns
# sorting by ID by team ensures unique line representation when we then push into lists
shift_interval <- shift_interval_gather %>% 
    select( -starts_with("away_player"), -starts_with("home_player"), 
            -starts_with( "on_ice"), -ends_with("_skaters"), -ends_with( "_goalie") ) %>% ungroup() %>% 
    arrange( game_date, start_cum, player_ha, desc(position_fd), player_id ) 
  
shift_interval_group_F_ev <- shift_interval %>% 
    filter( ev5on5, position_fd=="F" ) %>% 
    group_by( game_date, season, session_id, game_id4, period, start_cum, duration, our_ha ) %>% 
    summarise(
                    num_F_h = sum( player_ha=="H" ),
                    num_F_a = sum( player_ha=="A" ),
                    F_id_h_list  = list( player_id[ player_ha=="H"] ),
                    F_h_list     = list( last_name[ player_ha=="H"] ),
                    F_id_a_list  = list( player_id[ player_ha=="A"] ),
                    F_a_list     = list( last_name[ player_ha=="A"] )
  ) 
  
our_shift_interval_F <- shift_interval_group_F_ev %>% 
mutate(
  our_F_id_list = ifelse( our_ha=="H", F_id_h_list, F_id_a_list ),
  our_F_list    = ifelse( our_ha=="H", F_h_list,    F_a_list ),
  our_F_ids   = paste( our_F_id_list %>% unlist(), collapse=" " ),
  our_F_names = paste( our_F_list %>% unlist(), collapse=" " )
) 
    
shift_interval_group_pp <- shift_interval %>% 
    filter( strength=="pp", position_fd != "G" ) %>% 
    group_by( game_date, season, session_id, game_id4, skater_count, period, start_cum, duration, our_ha ) %>% 
    summarise(
                    num_h = sum( player_ha=="H" ),
                    num_a = sum( player_ha=="A" ),
                    id_h_list   = list( player_id[ player_ha=="H"] ),
                    name_h_list = list( last_name[ player_ha=="H"] ),
                    id_a_list   = list( player_id[ player_ha=="A"] ),
                    name_a_list = list( last_name[ player_ha=="A"] )
) 
  
our_shift_interval_pp <- shift_interval_group_pp %>% 
mutate(
  our_id_list   = ifelse( our_ha=="H", id_h_list, id_a_list ),
  our_name_list = ifelse( our_ha=="H", name_h_list, name_a_list ),
  our_ids   = paste( our_id_list %>% unlist(), collapse=" " ),
  our_names = paste( our_name_list %>% unlist(), collapse=" " )
) 

shift_interval_group_F_pp <- shift_interval %>% 
    filter( strength=="pp", skater_count=="5on4", position_fd=="F" ) %>% 
    group_by( game_date, season, session_id, game_id4, period, start_cum, duration, our_ha ) %>% 
    summarise(
                    num_F_h = sum( player_ha=="H" ),
                    num_F_a = sum( player_ha=="A" ),
                    F_id_h_list  = list( player_id[ player_ha=="H"] ),
                    F_h_list     = list( last_name[ player_ha=="H"] ),
                    F_id_a_list  = list( player_id[ player_ha=="A"] ),
                    F_a_list     = list( last_name[ player_ha=="A"] )
  ) 
  
our_shift_interval_F_pp <- shift_interval_group_F_pp %>% 
mutate(
  our_F_id_list = ifelse( our_ha=="H", F_id_h_list, F_id_a_list ),
  our_F_list    = ifelse( our_ha=="H", F_h_list,    F_a_list ),
  our_F_ids   = paste( our_F_id_list %>% unlist(), collapse=" " ),
  our_F_names = paste( our_F_list %>% unlist(), collapse=" " )
) 
```

```{r our F toi summary}
# Total EV5on5 TOI for season
# 3874 agrees with our D-men analysis
season_total_toi_ev <- our_shift_interval_F %>% ungroup() %>% summarise( toi=sum(duration) ) %>% unlist(use.names = F)
season_total_toi_ev
# back of the envelope
82 * 48

our_F_summary <- our_shift_interval_F %>% ungroup() %>% group_by( our_F_ids, our_F_names ) %>% 
            summarise( toi=sum(duration) ) %>% ungroup() %>% arrange( desc( toi )) %>% filter( toi > 0 ) %>% 
            mutate( toi_pct = round( toi/season_total_toi_ev*100,2 ) )

our_F_summary

our_F_lines <- our_F_summary %>% select( ids=our_F_ids, names=our_F_names, toi )
```

```{r our PP toi summary}
# Total 5on4 TOI for season
# 256 opportunities.  say 1.6 min
season_total_toi_pp <- our_shift_interval_pp %>% ungroup() %>% group_by(skater_count) %>% 
                        summarise( toi=sum(duration) ) %>% arrange( desc(toi) )
season_total_toi_pp
# back of the envelope: PPO x pp time
256 * 1.6

# Focus on 5on4
season_total_toi_5on4 <- season_total_toi_pp %>% filter( skater_count=="5on4" ) %>% select( toi ) %>% unlist()


our_pp_summary <- our_shift_interval_pp %>% ungroup() %>% 
            filter( skater_count=="5on4") %>% group_by( our_ids, our_names ) %>% 
            summarise( toi=sum(duration) ) %>% ungroup() %>% arrange( desc( toi )) %>% filter( toi > 0 ) %>% 
            mutate( toi_pct = round( toi/season_total_toi_5on4*100,2 ) )
our_pp_summary_F <- our_shift_interval_F_pp %>% ungroup() %>% 
            group_by( our_F_ids, our_F_names ) %>% 
            summarise( toi=sum(duration) ) %>% ungroup() %>% arrange( desc( toi )) %>% filter( toi > 0 ) %>% 
            mutate( toi_pct = round( toi/season_total_toi_5on4*100,2 ) )

pp_toi_cutoff <- 0 # gives 13 units
our_pp_summary %>% select( -our_ids ) %>% filter( toi > pp_toi_cutoff )

our_pp_lines <- our_pp_summary %>% select( ids=our_ids, names=our_names, toi ) %>% filter( toi > pp_toi_cutoff )
our_pp_lines

our_pp_lines %>% filter( str_detect( names, "Henrique" ) )


our_pp_lines_F <- our_pp_summary_F %>% select( ids=our_F_ids, names=our_F_names, toi, toi_pct ) %>% filter( toi > pp_toi_cutoff )
our_pp_lines_F


# individual PP TOI %
our_players_pp_toi <- shift_interval %>% filter( strength=="pp", player_ha==our_ha ) %>% 
  group_by( player_id, last_name, skater_count ) %>% 
  summarise(
  toi = sum(duration)
) %>% ungroup() %>% arrange( desc(toi) ) %>% filter( toi > pp_toi_cutoff )

our_players_pp_toi$last_name <- factor( our_players_pp_toi$last_name, levels=rev(unique(our_players_pp_toi$last_name ) ) )
  
our_players_pp_toi %>% slice( 1:15)
```

```{r PP TOI}
p.toi <- ggplot( our_players_pp_toi, aes(last_name, toi))
p.toi + geom_point() + coord_flip()
```


```{r pbp nest}
event_types_study <- c( "FAC", "BLOCK", "MISS", "SHOT", "GOAL", "PENL"  ) # , "ICING",  "OFFSIDE", "PENL"

pbp_spread <- pbp %>% 
    filter( event_type %in% event_types_study, home_skater_cnt >=4, away_skater_cnt >=4 ) %>% 
    select( -id, -xcoord, -ycoord, -event_length ) %>% distinct() %>% 
    left_join( our_games %>% select( season, game_id4, our_ha=ha ), by=c( "season", "game_id4" ) )
pbp_spread <- pbp_spread %>% 
  mutate(
    our_num_players   = ifelse( our_ha=="H", home_skater_cnt, away_skater_cnt ),
    their_num_players = ifelse( our_ha=="H", away_skater_cnt, home_skater_cnt ),
    our_en            = ifelse( our_ha=="H", is.na(home_goalie), is.na(away_goalie) ),
    their_en          = ifelse( our_ha=="H", is.na(away_goalie), is.na(home_goalie) ),
    our_num_skaters   = ifelse( !our_en,   our_num_players-1,   our_num_players ),
    their_num_skaters = ifelse( !their_en, their_num_players-1, their_num_players ),
    strength          = ifelse( our_num_players > their_num_players, "pp", 
                         ifelse( our_num_players < their_num_players, "sh", "ev" ) ),
    skater_count = paste0( our_num_skaters, "on", their_num_skaters ),
    skater_count = ifelse( our_en, paste0( skater_count, "_our_en"),
                        ifelse( their_en, paste0( skater_count, "_their_en"), skater_count ) )
  )

# CHECK
pbp_spread %>% select( our_num_skaters, their_num_skaters, our_en, their_en, strength, skater_count ) %>% 
  group_by( strength, skater_count, our_en, their_en ) %>% summarise( count=n() ) %>% ungroup() %>% arrange( desc(count)) 

# PP Goal strength
pbp_spread  %>% filter( event_type=="GOAL", event_team=="NJD", our_pp )  %>% select( pp_type)  %>% unlist()  %>% table


pbp_gather <- pbp_spread %>% 
                gather( player_label, player_id, away_p1_id:home_p6_id ) %>% 
                          filter( !is.na(player_id) ) %>% 
                          left_join( stage_roster %>% 
                              select( season, session_id, game_id4, 
                                      ha_number, nhl_id, last_name, 
                                      position_fd, player_team_short=team_short, player_ha=team_ha ), 
                            by = c( "season", "session_id", "game_id4", player_id = "nhl_id" )
                          )

pbp_gather <- pbp_gather %>% left_join(
                stage_roster %>% select( season, session_id, game_id4, 
                                         ha_number, event_player1_name=last_name, event_player1_fd=position_fd ), 
                by = c( "season", "session_id", "game_id4", event_player1 = "ha_number" )
) %>% left_join(
                stage_roster %>% select( season, session_id, game_id4, 
                                          ha_number, event_player2_name=last_name,  event_player2_fd=position_fd ), 
                by = c( "season", "session_id", "game_id4", event_player2 = "ha_number" )
)


# Drop extra columns
# sorting by ID by team ensures unique line representation when we then push into lists
pbp_multi <- pbp_gather %>% 
    select( -season, -session_id, -starts_with("away_player"), -starts_with("home_player"), 
            -starts_with( "on_ice"), -ends_with("_skaters"), -ends_with( "_goalie") ) %>% 
    arrange( game_date, start_cum, player_ha, desc(position_fd), player_id ) 
  
pbp_group_F_ev <- pbp_multi %>% 
    filter( ev5on5, position_fd=="F" ) %>% 
    group_by( game_date, game_id4, period, start_cum, our_ha, 
              event_type, etext, event_team, event_team_ha, homezone, event_player1_name, event_player2_name ) %>% 
    summarise(
                    num_F_h = sum( player_ha=="H" ),
                    num_F_a = sum( player_ha=="A" ),
                    F_id_h_list  = list( player_id[ player_ha=="H"] ),
                    F_h_list     = list( last_name[ player_ha=="H"] ),
                    F_id_a_list  = list( player_id[ player_ha=="A"] ),
                    F_a_list     = list( last_name[ player_ha=="A"] )
  ) 
  
our_pbp_F <- pbp_group_F_ev %>% 
mutate(
  our_F_id_list = ifelse( our_ha=="H", F_id_h_list, F_id_a_list ),
  our_F_list    = ifelse( our_ha=="H", F_h_list,    F_a_list ),
  our_F_ids   = paste( our_F_id_list %>% unlist(), collapse=" " ),
  our_F_names = paste( our_F_list %>% unlist(), collapse=" " )
) %>% filter(
  our_F_ids %in% our_F_lines$ids
)

our_pbp_F <- our_pbp_F %>% select( -starts_with( "num") )

exclude_pbp_F <- pbp_group_F_ev %>% 
mutate(
  our_F_id_list = ifelse( our_ha=="H", F_id_h_list, F_id_a_list ),
  our_F_list    = ifelse( our_ha=="H", F_h_list,    F_a_list ),
  our_F_ids   = paste( our_F_id_list %>% unlist(), collapse=" " ),
  our_F_names = paste( our_F_list %>% unlist(), collapse=" " )
) %>% filter(
  !our_F_ids %in% our_F_lines$ids
)
```

```{r PP pbp}
pbp_group_pp <- pbp_multi %>% 
    filter( strength=="pp" ) %>% 
    group_by( game_date, game_id4, period, start_cum, our_ha, 
              event_type, etext, event_team, event_team_ha, homezone, event_player1_name, event_player2_name, skater_count) %>% 
    summarise(
                    num_h = sum( player_ha=="H" ),
                    num_a = sum( player_ha=="A" ),
                    id_h_list   = list( player_id[ player_ha=="H"] ),
                    name_h_list = list( last_name[ player_ha=="H"] ),
                    id_a_list   = list( player_id[ player_ha=="A"] ),
                    name_a_list = list( last_name[ player_ha=="A"] )
) 
  
our_pbp_pp <- pbp_group_pp %>% 
mutate(
  our_id_list   = ifelse( our_ha=="H", id_h_list, id_a_list ),
  our_name_list = ifelse( our_ha=="H", name_h_list,    name_a_list ),
  our_ids       = paste( our_id_list %>% unlist(), collapse=" " ),
  our_names     = paste( our_name_list %>% unlist(), collapse=" " )
) %>% filter(
  # our_ids %in% our_pp_lines$ids
)

our_pbp_pp <- our_pbp_pp %>% select( -starts_with( "num") )



```

```{r faceoff}
fac_df <- our_pbp_F %>% ungroup() %>% filter( event_type=="FAC" ) 
fac_df <- fac_df %>% mutate(
  our_zs = ifelse( our_ha=="H", homezone,
                ifelse( homezone=="Def", "Off",
                        ifelse( homezone=="Off", "Def", "Neu" )))
)

fac_summary <- fac_df %>% 
                  group_by( our_F_ids, our_F_names ) %>% 
                  summarize( 
                    zs_o = sum(our_zs=="Off"),
                    zs_n = sum(our_zs=="Neu"),
                    zs_d = sum(our_zs=="Def"),
                    zs_o_pct = round( zs_o / (zs_o + zs_d ), 3 ),
                    fo_w = sum(event_team == our_team_short),
                    fo_l = sum(event_team != our_team_short),
                    fo_count = fo_w + fo_l,
                    fo_pct   = round( fo_w / fo_count, 3 )
                    ) %>% ungroup()

```

```{r penalties}
# penalties drawn/taken by any player, F or D
pen_df <- our_pbp_F %>% ungroup() %>% filter( event_type=="PENL" ) 

pen_summary <- pen_df %>% 
                  group_by( our_F_ids, our_F_names ) %>% 
                  summarize( 
                    # player_or = our_F_list %>% unlist() %>% str_to_upper(),
                    # pen      = sum( event_player1_name %in% player_or ),
                    # pen_draw = sum( event_player2_name %in% player_or ),
                    pen      = sum( event_team == our_team_short ),
                    pen_draw = sum( event_team != our_team_short ),
                    pen_diff = pen_draw - pen
                    ) %>% ungroup() %>% arrange( desc(pen_diff))

pen_df %>% filter( str_detect( our_F_names, "Palmieri")) %>% summarize(
                    pen      = sum( event_player1_name  == "PALMIERI", na.rm=T ),
                    pen_draw = sum( event_player2_name  == "PALMIERI", na.rm=T ),
                    pen_diff = pen_draw - pen
)

pen_all_df <- pbp %>% filter( event_type=="PENL" )
pen_df     <- pen_all_df %>% filter( event_team==our_team_short ) %>% group_by( event_p1_id ) %>% 
                summarise( pen=n() ) %>% 
                left_join( player_tbl %>% select(nhl_id, last_name ), by=c( "event_p1_id"="nhl_id") ) %>% 
                ungroup() %>% arrange( desc(pen))

pen_draw_df  <- pen_all_df %>% filter( event_team!=our_team_short ) %>% group_by( event_p2_id ) %>% 
                summarise( pen_draw=n() ) %>% 
                left_join( player_tbl %>% select(nhl_id, last_name ), by=c( "event_p2_id"="nhl_id") ) %>% 
                ungroup() %>% arrange( desc(pen_draw))

pen_combined <- pen_df %>% left_join( pen_draw_df %>% select(-last_name), by=c( "event_p1_id"="event_p2_id")) %>% 
                mutate( pen_diff = pen_draw - pen ) %>% arrange( desc(pen_diff))

write_csv( pen_combined, path=paste0( fig_dir, "/pen_draw.csv" ) )
```



```{r corsi}
shot_df <- our_pbp_F %>% ungroup() %>% filter( event_type %in% c( "BLOCK", "MISS", "SHOT", "GOAL") ) 

shot_summary <- shot_df %>% 
                  group_by( our_F_ids, our_F_names ) %>% 
                  summarize( 
                    cf_nhl = sum( event_team == our_team_short ),
                    ca_nhl = sum( event_team != our_team_short ),
                    ff_nhl = sum( event_team == our_team_short & event_type != "BLOCK" ),
                    fa_nhl = sum( event_team != our_team_short & event_type != "BLOCK" ),
                    ff_pct_nhl   = round( ff_nhl / (ff_nhl + fa_nhl ), 3 ),
                    cf_pct_nhl   = round( cf_nhl / (cf_nhl + ca_nhl ), 3 )
                    ) %>% ungroup()
```

```{r PP corsi by line}
shot_pp_df <- our_pbp_pp %>% ungroup() %>% filter( event_type %in% c( "BLOCK", "MISS", "SHOT", "GOAL") ) 

shot_pp_summary <- shot_pp_df %>% 
                  group_by( our_ids, our_names, skater_count ) %>% 
                  summarize( 
                    cf_nhl = sum( event_team == our_team_short ),
                    ff_nhl = sum( event_team == our_team_short & event_type != "BLOCK" ),
                    gf     = sum( event_team == our_team_short & event_type == "GOAL" ),
                    ga     = sum( event_team != our_team_short & event_type == "GOAL" )

                    ) %>% ungroup() %>% arrange( desc(ff_nhl ))

pp_summary <- shot_pp_summary %>% left_join( our_pp_lines, by=c( "our_ids"="ids" ) ) %>% 
                      mutate(
                        ff_nhl_60 = round( ff_nhl / toi * 60, 3 ),
                        gf_nhl_60 = round( gf     / toi * 60, 3 )
                      ) %>% select( -our_ids ) %>% arrange( desc(gf_nhl_60) )

# pp5on4_summary %>% View
```

```{r PP corsi individual}
shot_player_df <- pbp_multi %>% filter( event_type %in% c( "BLOCK", "MISS", "SHOT", "GOAL") ) 

shot_player_df <- shot_player_df %>% filter( player_team_short=="NJD" ) %>% 
                  group_by( player_id, last_name, position_fd, strength, skater_count ) %>% 
                  summarize( 
                    cf_nhl = sum( event_team == our_team_short ),
                    ca_nhl = sum( event_team != our_team_short ),
                    ff_nhl = sum( event_team == our_team_short & event_type != "BLOCK" ),
                    fa_nhl = sum( event_team != our_team_short & event_type != "BLOCK" ),
                    gf_nhl = sum( event_team == our_team_short & event_type == "GOAL" ),
                    ga_nhl = sum( event_team != our_team_short & event_type == "GOAL" ),
                    ff_pct_nhl   = round( ff_nhl / (ff_nhl + fa_nhl ), 3 ),
                    cf_pct_nhl   = round( cf_nhl / (cf_nhl + ca_nhl ), 3 ),
                    gf_pct_nhl   = round( gf_nhl / (gf_nhl + ga_nhl ), 3 )
                    ) %>% ungroup()

shot_player_df <- shot_player_df %>% left_join( our_players_pp_toi %>% select( player_id, skater_count, toi ),
                                                by=c( "player_id", "skater_count" ) )

shot_player_df <- shot_player_df %>% mutate(
                        ff_nhl_60 = round( ff_nhl / toi * 60, 3 ),
                        gf_nhl_60 = round( gf_nhl / toi * 60, 3 )
)

shot_player_df %>% filter( strength=="pp", skater_count=="5on4" ) %>% select( -ca_nhl, -fa_nhl, -contains( "pct") ) %>%  View

```

```{r goals}
goals_df <- our_pbp_F %>% ungroup() %>% filter( event_type %in% c( "GOAL") ) 

goals_summary <- goals_df %>% 
                  group_by( our_F_ids, our_F_names ) %>% 
                  summarize( 
                    gf = sum( event_team == our_team_short ),
                    ga = sum( event_team != our_team_short ),
                    gf_pct = round( gf / (gf + ga ), 3 )
                    ) %>% ungroup()
```


```{r gio check NHL}
gionta_df <- shot_df %>% filter( str_detect( our_F_names, "Gionta"))
(gionta_df$event_team=="NJD") %>% table() %>% prop.table()

gionta_df <- shot_df %>% filter( str_detect( our_F_names, "Gionta"), str_detect( our_F_names, "Tootoo"), str_detect( our_F_names, "Farnham") )
(gionta_df$event_team=="NJD") %>% table() %>% prop.table()

gionta_df <- shot_df %>% filter( str_detect( our_F_names, "Gionta"), str_detect( our_F_names, "Ruutu"), str_detect( our_F_names, "Farnham") )
(gionta_df$event_team=="NJD") %>% table() %>% prop.table()

gionta_df <- shot_df %>% filter( str_detect( our_F_names, "Kennedy"), str_detect( our_F_names, "Josefson"), str_detect( our_F_names, "Kalinin") )
(gionta_df$event_team=="NJD") %>% table() %>% prop.table()
```






```{r chances clean up}

shots_all <- shots_all_df %>% distinct() %>% 
  filter( !(game_id4=="0094" & start_cum==13.533 & is.na(comment)) ) %>%  # bad redundant point
  mutate(
                    id = on_ice_ids %>% gsub( "NA", "", . ) %>% str_split( " " ) 
) %>% unnest() %>% mutate(
  id = id %>% as.numeric()
) 

shots_all <- shots_all %>% left_join(
    stage_roster %>% select( game_date, season, session_id, game_id4, nhl_id, last_name, team_short, position, player_ha=team_ha ), 
                      by=c( "season", "session_id", "game_id4", "id"="nhl_id" )
) %>% mutate(
  position_fd = ifelse( position=="G", "G", 
                        ifelse(position=="D", "D", "F" ) )
)
shots_all <- shots_all %>% filter( position_fd != "G" )  %>% ungroup() %>% 
              arrange( game_date, start_cum, player_ha, desc(position_fd), id )  ## id sort guarantees unique lines

shots_ev_F <- shots_all %>% filter( ev5on5, position_fd=="F" )

shots_group_ev_F <- shots_ev_F %>% group_by( season, session_id, game_id4, start_cum, our_ha=ha,
                                             event_team, shotcolor, shot, shooter, attribute, comment ) %>% 
  summarise(
                  F_id_h_list  = list( id[ player_ha=="H"] ),
                  F_h_list     = list( last_name[ player_ha=="H"] ),
                  F_id_a_list  = list( id[ player_ha=="A"] ),
                  F_a_list     = list( last_name[ player_ha=="A"] )
) 
  
our_shots_F <- shots_group_ev_F %>% 
mutate(
  our_F_id_list = ifelse( our_ha=="H", F_id_h_list, F_id_a_list ),
  our_F_list    = ifelse( our_ha=="H", F_h_list,    F_a_list ),
  our_F_ids   = paste( our_F_id_list %>% unlist(), collapse=" " ),
  our_F_names = paste( our_F_list %>% unlist(), collapse=" " ),
  our_num_F = our_F_list %>% unlist() %>% length()
) 
```

```{r PP chances}
# 5on4 chances
chances_5on4 <- shots_all %>% filter( strength=="PP 5v4", shot != "BLOCK", team_short=="NJD", event_team=="NJD" ) 

chances_5on4_summary <- chances_5on4 %>% group_by( id, last_name ) %>% 
                        summarise(
                          ff = n(), # Blocks already filtered out, as are all opponent shota ttempts
                          green_f = sum( shotcolor=="GREEN" ),
                          blue_f  = sum( shotcolor=="BLUE" )
                        )

pp_player_df <- shot_player_df %>% filter( strength=="pp", skater_count=="5on4" ) %>% 
                            select( -ca_nhl, -fa_nhl, -contains( "pct") ) %>%  
                            left_join( chances_5on4_summary %>% select(-last_name), by=c( "player_id"="id" ) ) %>% 
                             mutate(
                              ff_60 = round( ff / toi * 60, 3 ),
                              green_60 = round( green_f / toi * 60, 3 ),
                              blue_60 = round( blue_f / toi * 60, 3 ),
                              greenblue_60 = green_60 + blue_60
)

player_games_played <- stage_roster %>% filter( team_short=="NJD" ) %>% group_by( nhl_id, last_name ) %>% 
                        summarise( game=n() ) %>% ungroup()

pp_write <- pp_player_df %>% filter( toi > 10 ) %>% 
            left_join( player_games_played %>% select( player_id=nhl_id, game), by="player_id" ) %>% 
            mutate(
              pp_toi_gm = toi/game
            ) %>% 
            select( -player_id, -strength, -skater_count, -cf_nhl ) %>% 
            select( last_name, position_fd, game, toi, pp_toi_gm, everything() ) %>% arrange( desc(position_fd), desc(pp_toi_gm))

write_csv( pp_write, path = paste0( fig_dir, "/pp5on4.csv" ) )

```

```{r chances by line}
chances_summary <- our_shots_F %>% ungroup() %>% 
        group_by( our_F_ids ) %>% 
        summarise(
                  cf = sum( event_team == our_team_short ),
                  ca = sum( event_team != our_team_short ),
                  c_net = cf-ca,
                  ff = sum( event_team == our_team_short & shot != "BLOCK" ),
                  fa = sum( event_team != our_team_short & shot != "BLOCK" ),
                  f_net = ff-fa,
                  ff_pct   = round( ff / (ff + fa ), 3 ),
                  cf_pct   = round( cf / (cf + ca ), 3 ),
                  green_f = sum( (event_team == our_team_short) & (shot != "BLOCK") & (shotcolor=="GREEN") ),
                  green_a = sum( (event_team != our_team_short) & (shot != "BLOCK") & (shotcolor=="GREEN") ),
                  green_net = green_f - green_a,
                  green_f_pct = round( green_f / (green_f + green_a ), 3 ),
                  blue_f = sum( (event_team == our_team_short) & (shot != "BLOCK") & (shotcolor=="BLUE") ),
                  blue_a = sum( (event_team != our_team_short) & (shot != "BLOCK") & (shotcolor=="BLUE") ),
                  blue_net = blue_f - blue_a,
                  blue_f_pct = round( blue_f / (blue_f + blue_a ), 3 ),
                  greenblue_f = green_f + blue_f,
                  greenblue_a = green_a + blue_a,
                  greenblue_net = greenblue_f - greenblue_a,
                  greenblue_f_pct = round( greenblue_f / (greenblue_f + greenblue_a ), 3 )
                  
        )

```

```{r combine}
our_F_stats <- our_F_lines %>% 
                left_join( fac_summary %>% ungroup(),  by=c( "ids"="our_F_ids", "names"="our_F_names" )) %>% 
                left_join( pen_summary %>% ungroup(),  by=c( "ids"="our_F_ids", "names"="our_F_names" )) %>% 
                left_join( shot_summary %>% ungroup(), by=c( "ids"="our_F_ids", "names"="our_F_names" )) %>% 
                left_join( goals_summary %>% ungroup(), by=c( "ids"="our_F_ids", "names"="our_F_names" )) %>% 
                left_join( chances_summary %>% ungroup(), by=c( "ids"="our_F_ids" )) 

our_F_stats <- our_F_stats %>% mutate(
                cf_60 = round( cf / toi * 60, 3 ),
                ca_60 = round( ca / toi * 60, 3 ),
                c_net_60 = round( c_net / toi * 60, 3 ),
                green_f_60 = round( green_f / toi * 60, 3 ),
                green_a_60 = round( green_a / toi * 60, 3 ),
                green_net_60 = round( green_net / toi * 60, 3 ),
                blue_f_60 = round( blue_f / toi * 60, 3 ),
                blue_a_60 = round( blue_a / toi * 60, 3 ),
                blue_net_60 = round( blue_net / toi * 60, 3 ),
                greenblue_f_60 = round( greenblue_f / toi * 60, 3 ),
                greenblue_a_60 = round( greenblue_a / toi * 60, 3 ),
                greenblue_net_60 = round( greenblue_net / toi * 60, 3 ),
                pen_diff_60     = round( pen_diff / toi * 60, 3 )
  
  
)

write_csv( our_F_stats, path=paste0(fig_dir, "/njd_f_lines.csv" ) )

```


```{r glimpse}
our_lines <- our_F_stats %>% filter( toi > 30 )

p.lines <- ggplot( our_lines, aes( cf_pct, cf_pct_nhl ))
p.lines + geom_point() + 
          geom_abline( intercept=0,slope=1) +  
          coord_fixed() + geom_smooth(method="lm", se=F)

p.lines <- ggplot( our_lines, aes( ff_pct, ff_pct_nhl ))
p.lines + geom_point() + 
          geom_abline( intercept=0,slope=1) +  
          coord_fixed() + geom_smooth(method="lm", se=F)

p.lines <- ggplot( our_lines  %>% filter( toi > 50 ), aes( cf_pct, green_f_pct ))
p.lines + geom_point(aes(size=toi)) + 
          geom_vline( xintercept=0.5) +
          geom_hline( yintercept=0.5) +
          geom_text(aes(label=names), nudge_y=0.01 ) +
          geom_abline( intercept=0,slope=1) +
           geom_smooth(se=F) + coord_fixed()

p.lines <- ggplot( our_lines  %>% filter( toi > 50 ), aes( cf_pct, blue_f_pct ))
p.lines + geom_point(aes(size=toi)) + 
          geom_vline( xintercept=0.5) +
          geom_hline( yintercept=0.5) +
          geom_text(aes(label=names) ) +
          geom_abline( intercept=0,slope=1) +
           geom_smooth(se=F) + coord_fixed()

p.lines <- ggplot( our_lines  %>% filter( toi > 50 ), aes( green_f_pct, blue_f_pct ))
p.lines + geom_point(aes(size=toi)) +
          geom_vline( xintercept=0.5) +
          geom_hline( yintercept=0.5) +
          geom_text(aes(label=names), nudge_y=0.01 ) +
          geom_abline( intercept=0,slope=1) +
           geom_smooth(se=F) + coord_fixed()


p.lines <- ggplot( our_lines  %>% filter( toi > 50 ), aes( cf_pct, greenblue_f_pct ))
p.lines + geom_point(aes(size=toi)) + 
          geom_abline( intercept=0,slope=1) +  
           geom_smooth(se=F) + coord_fixed()

p.lines <- ggplot( our_lines, aes( zs_o_pct, green_f_pct ))
p.lines + geom_point(aes(size=toi)) + 
          geom_text( aes(label=names))

p.lines <- ggplot( our_lines %>% filter( str_detect(names, "O'Neill")), aes( cf_pct_nhl, cf_pct ))
p.lines + geom_point(aes(size=toi)) + 
          geom_text( aes(label=names))

our_lines %>% filter( str_detect(names, "Gionta")) %>% select( names, toi, cf_pct, cf_pct_nhl, green_f_pct, green_net_60)
```




```{r NJD F pair summary}
njd_team_gp_ev$toi %>% sum()

defensemen_h2h_ev <- njd_h2h_ev %>% filter( position_fd_1=="D", position_fd_2=="D" ) %>% arrange(
                                    desc(toi_1), desc(toi)
) %>% select( -matches("position|team_comp|faceoff|is|fo|num|rank|team_short|shoots"))

defensemen_gp_ev <- defensemen_h2h_ev %>% group_by( nhl_id_1, last_name_1, toi_1 ) %>% mutate(
                      toi_pct          = round( toi / first(toi) * 100, 1),
                      toi_wo           = toi - first(toi),  
                      cf_wo            = cf -  first(cf),
                      ca_wo            = ca -  first(ca),
                      c_net_wo         = c_net - first(c_net),
                      green_net_wo     = green_net - first(green_net),
                      blue_net_wo      = blue_net - first(blue_net),
                      greenblue_f_wo   = greenblue_f - first(greenblue_f),
                      greenblue_a_wo   = greenblue_a - first(greenblue_a),
                      greenblue_net_wo = greenblue_net - first(greenblue_net),
                      c_net_60_wo      = round( c_net  / toi_wo * 60, 3 ),
                      c_net_60_wowy    = c_net_60 - c_net_60_wo,
                      green_net_60_wo  = round( green_net  / toi_wo * 60, 3 ),
                      green_net_60_wowy= green_net_60 - green_net_60_wo,
                      blue_net_60_wo   = round( blue_net  / toi_wo * 60, 3 ),
                      blue_net_60_wowy = blue_net_60 - blue_net_60_wo,
                      greenblue_net_60_wo = round( greenblue_net  / toi_wo * 60, 3 ),
                      greenblue_net_60_wowy = greenblue_net_60 - greenblue_net_60_wo,
                      greenblue_f_pct_wo  = round( greenblue_f_wo / cf_wo * 100, 3 ),
                      greenblue_a_pct_wo  = round( greenblue_a_wo / ca_wo * 100, 3 )
)

write_csv( defensemen_gp_ev, path=paste0(fig_dir, "/njd_d_pairs.csv" ))
```


```{r h-r PP stats}
njd_url <- "http://www.hockey-reference.com/teams/NJD/2016.html"

njd_html <- njd_url %>% read_html()
njd_summary <- njd_html %>% html_node( "#skaters" ) %>% html_table(header=F)
names( njd_summary ) <- njd_summary[2,]
njd_summary <- njd_summary[ -(1:2), ]

njd_season_summary <- njd_summary %>% separate( Player, c( "first_name", "last_name"), sep = " " ) %>% rename(
  g_pp = PPG,
  g_sh = SHG,
  a_ev = `EV.1`,
  a_pp = PP,
  a_sh = SH
)

our_players_pp_summary <- our_players_pp_toi %>% left_join( njd_season_summary %>% select( last_name, g_pp, a_pp ), by="last_name" )

write_csv( our_players_pp_summary %>% filter( skater_count=="5on4"), path=paste0(fig_dir, "/njd_pp.csv" ))

```









