---
title: "NJ Devils EV5on5 Chances - through 50 Games"
geometry: margin=1cm
output: word_document
fontsize: 10pt
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, tidy=TRUE, cache=FALSE, OutDec = ",")
```

```{r more_setup, include=F}
library( njdanalytics )
# source( paste0( nhl_dir$base, "/packages/njdanalytics/sandbox/charts.R" ) )

nhl_db <- setup_nhl_db()
# player_tbl           <- tbl( nhl_db, "player"               ) %>% collect()
# stage_game           <- tbl( nhl_db, "stage_game"           )
# stage_roster         <- tbl( nhl_db, "stage_roster"         )
# stage_playbyplay     <- tbl( nhl_db, "stage_playbyplay"     )
# stage_shift_interval <- tbl( nhl_db, "stage_shift_interval" )
team_score           <- tbl( nhl_db, "team_score"           )
# game_player          <- tbl( nhl_db, "game_player"          )

# njd_games has game_number and game_id4 to join different data sources
this_season     <- "20152016"
this_session_id <- "2"
njd_games            <- team_score %>% filter( season==this_season, session_id==this_session_id, team_short=="NJD" ) %>%
  collect() %>% arrange( game_date )
njd_games            <- add_team_score_label( njd_games, our_team="NJD" ) %>%
  select( game_number, season, session_id, game_id4, ha, opp_team_short, game_label )
```

```{r data sets}
load( file=paste0( nhl_dir$shots, "/njd_through_50.RData" ) )
njd_summary_spreadsheet <- paste0( nhl_dir$shot, "/NJD_through_gm50.xlsx" )
njd_summary <- read_excel( njd_summary_spreadsheet, skip=1)

last_names  <- njd_summary$Player[ njd_summary$Gm > 5 ] %>%  na.omit() 
last_names  <- last_names[ !last_names %in% c( "NJD") ]

njd_players_by_game_ev <- njd_players_by_game %>% filter( strength=="ev5on5", metric %in% c( "green", "blue" ), 
  nhl_id !=1, position_fd != "G" ) %>% 
                select( -season, -session_id, -strength, -ha_number, -team_short, -game_id4 )

goals <- njd_players_by_game  %>% filter( metric=="goal", strength=="ev5on5") %>% 
  select( nhl_id, game_number, gf=scf, ga=sca, g_net=sc_net, g_total=sc_total)

njd_players_by_game_ev <- njd_players_by_game_ev %>% left_join( goals, by=c("nhl_id", "game_number" ) )
njd_players_by_game_ev[ is.na(njd_players_by_game_ev) ] <- 0

window_size <- 5
players_ma <- njd_players_by_game_ev %>% group_by( nhl_id, last_name, position_fd, number, metric ) %>%
  arrange(
    desc(game_number)
  ) %>% filter( n() >= window_size ) %>%
  mutate(
    scf_ma    = rollmean( x=scf,   window_size, align="left", fill=NA ),
    sca_ma    = rollmean( x=sca, window_size, align="left", fill=NA ),
    sc_net_ma = rollmean( x=sc_net, window_size, align="left", fill=NA ),
    scf_i_ma  = rollmean( x=scf_i, window_size, align="left", fill=NA ),
    toi_gm_ma = rollmean( x=toi, window_size, align="left", fill=NA )
  ) %>% ungroup() %>% arrange( position_fd, nhl_id, metric, game_number)

 players_ma$metric <- factor( players_ma$metric, levels=c( "green", "blue") )
```

```{r goals and corsi}
players_green <- players_ma %>% filter( metric=="green")

p.goals <- ggplot( players_green, aes(x=c_net, y=g_net) )
p.goals + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) +
  geom_jitter(width=0.5,height=0.5,alpha=0.4,color="navy") + stat_smooth() +
  ggtitle( "EV Goal Diff vs. Corsi, NJD player-games")
```

```{r goals and chances}
p.goals <- ggplot( players_green, aes(x=sc_net, y=g_net) )
p.goals + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) +
  geom_jitter(width=0.5,height=0.5,alpha=0.4,color="navy") + stat_smooth() +
 ggtitle( "EV Goal Diff vs. Green chances, NJD player-games")
```

```{r Corsi and chances}
p.sc <- ggplot( players_green, aes(x=c_net, y=sc_net) )
p.sc + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) +
  geom_jitter(width=0.5,height=0.5,alpha=0.4,color="navy") + stat_smooth() +
 ggtitle( "EV Green chances vs. Corsi, NJD player-games")
```

```{r models, echo=TRUE}
# Goal diff modeled with Green chances
summary( lm(data=players_green, g_net ~ sc_net ))
with( players_green, cor( g_net, sc_net ) )

# Goal diff modeled with Corsi
summary( lm(data=players_green, g_net ~ c_net ))
with( players_green, cor( g_net, c_net ) )

# Chances modeled with Corsi
summary( lm(data=players_green, sc_net ~ c_net ))
with( players_green, cor( sc_net, c_net ) )
```



<!-- ```{r charts, fig.width=7.5, fig.height=3 } -->

<!-- # my_labeller <- label_bquote( -->
<!-- #   rows -->
<!-- # ) -->

<!-- base_size <- 9 -->
<!-- y_lim_min <- -4 -->
<!-- y_lim_max <- 5.9 -->
<!-- x_max <- 50 -->

<!-- for( this_last_name in last_names ) { -->
<!--   # message( "Process ", this_last_name ) -->
<!--   # this_last_name <- "CAMMALLERI" -->
<!--   # if( this_last_name=="BOUCHER" ) next() -->

<!--   this_player <- players_ma %>% filter( last_name==this_last_name  ) %>% select( 1, 2, 10, 11, 18:23 ) -->
<!--   this_player <- this_player %>% gather( foragainst, value, -c(1,2,3,5,6) ) %>% filter( foragainst %in% c("scf_ma", "sca_ma", "sc_net_ma")) -->

<!--   this_player <- this_player %>% transform( -->
<!--     foragainst = factor( foragainst, labels=c( "For", "Against", "Net")) -->
<!--   ) -->
<!--   this_title <- paste( this_player[1,]$number, this_player[1,]$last_name ) -->

<!--   g.player <- ggplot( this_player %>% filter(metric %in% c("green", "blue")), aes(x=game_number,y=value) ) -->
<!--   g.player <- g.player + geom_hline(yintercept=c(-2,2), color="grey") + geom_hline(yintercept=0, color="darkred") + -->
<!--     # stat_smooth(color="lightgrey", se=F) + -->
<!--     geom_line(aes(color=metric),size=1) +  -->
<!--     geom_point(aes(color=metric),size=1.6) + -->
<!--     scale_color_manual( "Chance", labels=c( "Blue", "Green" ), values=c( "blue"="slateblue", "green"="yellowgreen"), guide=F) + -->
<!--     scale_x_continuous( "Game Number",limits=c(0,x_max),breaks=seq(0,100,5) ) +  -->
<!--     scale_y_continuous( "Chances", limits=c(y_lim_min, y_lim_max), breaks=seq(-50,50,1) ) +  -->
<!--     facet_grid( metric ~ foragainst, switch="y" ) + theme_bw(base_size = base_size) +  -->
<!--     ggtitle( this_title ) -->

<!--   print(g.player) -->
<!--   cat( sprintf( "\n" ) ) -->
<!-- } -->
<!-- ``` -->


